# Peer 4 - Laptop
peer_id = 4
bind_ip = 0.0.0.0
control_bind_port = 6006
snapshot_bind_port = 6007

render_hz     = 60
network_hz    = 60
simulation_hz = 120

peer1_host = 172.16.0.91
peer1_control_port = 6000
peer1_snapshot_port = 6001

peer2_host = 172.16.0.91
peer2_control_port = 6002
peer2_snapshot_port = 6003

peer3_host = 127.0.0.1
peer3_control_port = 6004
peer3_snapshot_port = 6005