# Peer 1 local test config
peer_id = 1
bind_ip = 127.0.0.1
control_bind_port = 6000
snapshot_bind_port = 6001

render_hz     = 60
network_hz    = 60
simulation_hz = 120

peer2_host = 127.0.0.1
peer2_control_port = 6002
peer2_snapshot_port = 6003

peer3_host = 127.0.0.1
peer3_control_port = 6004
peer3_snapshot_port = 6005

peer4_host = 127.0.0.1
peer4_control_port = 6006
peer4_snapshot_port = 6007
