#version 450

#define MAX_SPARK_LIGHTS 32

struct PointLight {
    vec4 pos_radius; // xyz = position, w = radius
    vec4 col_int;    // rgb = color,    w = intensity
};

layout(set = 0, binding = 0) uniform UniformBufferObject {
    mat4 view;
    mat4 proj;
    vec4 cameraPos;
    vec4 sunDir_Int;
    vec4 moonDir_Int;
    vec4 ambient;

    PointLight sparkLights[MAX_SPARK_LIGHTS];
    ivec4 sparkLightCount_pad; // x = count
} ubo;

// Instance buffer attributes
layout(location = 0) in vec4 inPosSize; // xyz pos, w size
layout(location = 1) in vec4 inColor;   // rgba

layout(location = 0) out vec2 vUV;
layout(location = 1) out vec4 vColor;

void main()
{
    // Two triangles (6 verts) generated by gl_VertexIndex
    vec2 quad[6] = vec2[](
        vec2(-1.0, -1.0), vec2( 1.0, -1.0), vec2( 1.0,  1.0),
        vec2(-1.0, -1.0), vec2( 1.0,  1.0), vec2(-1.0,  1.0)
    );

    vec2 p = quad[gl_VertexIndex];
    vUV = p * 0.5 + 0.5;
    vColor = inColor;

    // Extract camera right/up in world space from view matrix
    // view is world->view, so transpose(mat3(view)) gives view->world rotation
    mat3 invViewRot = transpose(mat3(ubo.view));
    vec3 camRight = invViewRot[0];
    vec3 camUp    = invViewRot[1];

    vec3 worldPos = inPosSize.xyz + (camRight * p.x + camUp * p.y) * inPosSize.w;

    gl_Position = ubo.proj * ubo.view * vec4(worldPos, 1.0);
}
